apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy6
  labels:
    app: buggy6core
spec:
  replicas: 3
  selector:
    matchLabels:
      service: buggy6service
  template:
    metadata:
      labels:
        app: buggy6core
        service: buggy6service
    spec:
      containers:
      - name: buggy6
        image: tatacr.azurecr.io/sample
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: buggy6service
  labels:
    app: buggy6
    service: webapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: buggy6service